services:
  - type: web
    name: mtb-multiplayer-server
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
